insert into models values(0,'Toyota','Paseo');
insert into models values(1,'Dodge','Stratus');
insert into models values(2,'Dodge','Intrepid');
insert into models values(3,'Dodge','Ram Van 3500');
insert into models values(4,'Dodge','Stealth');
insert into models values(5,'Ford','Crown Victoria');
insert into models values(6,'Ford','Thunderbird');
insert into models values(7,'Ford','Aerostar');
insert into models values(8,'Ford','Econoline E350');
insert into models values(9,'Buick','Century');
insert into models values(10,'Buick','Hearse');
insert into models values(11,'Volkswagen','Jetta');
insert into models values(12,'Mitsubishi','Galant');
insert into models values(13,'Suzuki','X-90');
insert into models values(14,'Suzuki','Esteem');
insert into models values(15,'Porsche','911');
insert into models values(16,'Chevrolet','Tahoe');
insert into models values(17,'Chevrolet','Express 2500');
insert into models values(18,'Chevrolet','Suburban 2500');
insert into models values(19,'Kia','Sephia');
insert into models values(20,'Lexus','GS');
insert into models values(21,'Lexus','ES');
insert into models values(22,'Subaru','Impreza');
insert into models values(23,'BMW','Z3');
insert into models values(24,'Lamborghini','Diablo');
insert into models values(25,'Acura','SLX');
insert into models values(26,'GMC','Jimmy');
insert into models values(27,'Chevrolet','Sportvan G10');
insert into models values(28,'GMC','Rally Wagon 2500');
insert into models values(29,'Mitsubishi','Expo');
insert into models values(30,'Dodge','Ram Van B350');
insert into models values(31,'Subaru','Justy');
insert into models values(32,'Porsche','968');
insert into models values(33,'Alfa Romeo','Spider');
insert into models values(34,'Jeep','Wrangler');
insert into models values(35,'Porsche','Boxster');
insert into models values(36,'Jaguar','XK Series');
insert into models values(37,'Oldsmobile','LSS');
insert into models values(38,'Mercedes-Benz','300TE');
insert into models values(39,'Mercedes-Benz','600SEL');
insert into models values(40,'Volvo','S80');
insert into models values(41,'Scion','xB');
insert into models values(42,'Volkswagen','Touareg');
insert into models values(43,'Ford','Five Hundred');
insert into models values(44,'Ford','E250');
insert into models values(45,'BMW','X3');
insert into models values(46,'Mitsubishi','Outlander');
insert into models values(47,'Audi','TT');
insert into models values(48,'Cadillac','Escalade ESV');
insert into models values(49,'Lincoln','LS');
insert into models values(50,'Chevrolet','Avalanche 1500');
insert into models values(51,'Isuzu','Axiom');
insert into models values(52,'Isuzu','Rodeo Sport');
insert into models values(53,'Jaguar','S-Type');
insert into models values(54,'Nissan','Titan');
insert into models values(55,'Maybach','62');
insert into models values(56,'Chrysler','Crossfire');
insert into models values(57,'Chrysler','Pacifica');
insert into models values(58,'Land Rover','Discovery Series II');
insert into models values(59,'Ford','Fiesta');
insert into models values(60,'Hyundai','XG300');
insert into models values(61,'Toyota','T100');
insert into models values(62,'Volvo','960');
insert into models values(63,'Dodge','Dakota Club');
insert into models values(64,'Dodge','Viper');
insert into models values(65,'Ford','Bronco');
insert into models values(66,'Ford','Taurus');
insert into models values(67,'Ford','E-Series');
insert into models values(68,'Ford','F350');
insert into models values(69,'Lincoln','Continental');
insert into models values(70,'Buick','Regal');
insert into models values(71,'Buick','Skylark');
insert into models values(72,'Audi','Cabriolet');
insert into models values(73,'Mitsubishi','Mighty Max');
insert into models values(74,'Pontiac','Grand Prix');
insert into models values(75,'Pontiac','Trans Sport');
insert into models values(76,'Pontiac','Sunfire');
insert into models values(77,'Saab','900');
insert into models values(78,'Chevrolet','3500');
insert into models values(79,'Chevrolet','Beretta');
insert into models values(80,'Chevrolet','Express 3500');
insert into models values(81,'Chevrolet','G-Series 2500');
insert into models values(82,'Chevrolet','G-Series G30');
insert into models values(83,'Chevrolet','S10');
insert into models values(84,'Nissan','Sentra');
insert into models values(85,'Jeep','Grand Cherokee');
insert into models values(86,'Jeep','Cherokee');
insert into models values(87,'Lexus','SC');
insert into models values(88,'Lexus','LS');
insert into models values(89,'Honda','Civic');
insert into models values(90,'Chrysler','Cirrus');
insert into models values(91,'Chrysler','LHS');
insert into models values(92,'BMW','7 Series');
insert into models values(93,'GMC','1500');
insert into models values(94,'Infiniti','G');
insert into models values(95,'Isuzu','Hombre');
insert into models values(96,'Isuzu','Rodeo');
insert into models values(97,'Oldsmobile','Ciera');
insert into models values(98,'Oldsmobile','Silhouette');
insert into models values(99,'BMW','5 Series');
insert into models values(100,'Plymouth','Sundance');
insert into models values(101,'Volvo','240');
insert into models values(102,'Dodge','Ram Van B150');
insert into models values(103,'Chevrolet','Impala SS');
insert into models values(104,'Audi','100');
insert into models values(105,'Alfa Romeo','164');
insert into models values(106,'GMC','Vandura G1500');
insert into models values(107,'GMC','Vandura G2500');
insert into models values(108,'Honda','Del Sol');
insert into models values(109,'Audi','A8');
insert into models values(110,'Chevrolet','Venture');
insert into models values(111,'Hyundai','Tiburon');
insert into models values(112,'Oldsmobile','Regency');
insert into models values(113,'Chevrolet','Metro');
insert into models values(114,'Chevrolet','Tracker');
insert into models values(115,'Subaru','Forester');
insert into models values(116,'Volkswagen','New Beetle');
insert into models values(117,'GMC','Sonoma Club');
insert into models values(118,'Infiniti','M');
insert into models values(119,'Dodge','Ramcharger');
insert into models values(120,'Jeep','Liberty');
insert into models values(121,'Saturn','VUE');
insert into models values(122,'Volvo','C70');
insert into models values(123,'Scion','xA');
insert into models values(124,'Acura','TSX');
insert into models values(125,'Ford','Freestar');
insert into models values(126,'Ford','Excursion');
insert into models values(127,'Porsche','Carrera GT');
insert into models values(128,'Suzuki','Daewoo Lacetti');
insert into models values(129,'BMW','645');
insert into models values(130,'BMW','745');
insert into models values(131,'BMW','X5');
insert into models values(132,'Mitsubishi','Lancer');
insert into models values(133,'Cadillac','XLR');
insert into models values(134,'Maserati','Spyder');
insert into models values(135,'Toyota','Prius');
insert into models values(136,'Toyota','Sequoia');
insert into models values(137,'Lexus','GX');
insert into models values(138,'Mercury','Marauder');
insert into models values(139,'Spyker','C8 Spyder');
insert into models values(140,'Hyundai','XG350');
insert into models values(141,'Infiniti','G35');
insert into models values(142,'Chevrolet','Colorado');
insert into models values(143,'Nissan','Murano');
insert into models values(144,'Ford','Th!nk');
insert into models values(145,'Ford','ZX2');
insert into models values(146,'Mazda','Protege5');
insert into models values(147,'Toyota','T100 Xtra');
insert into models values(148,'Toyota','Xtra');
insert into models values(149,'Volvo','850');
insert into models values(150,'Ford','Windstar');
insert into models values(151,'Ford','Escort');
insert into models values(152,'Ford','Aspire');
insert into models values(153,'Ford','Club Wagon');
insert into models values(154,'Mercedes-Benz','SL-Class');
insert into models values(155,'Lincoln','Town Car');
insert into models values(156,'Lincoln','Mark VIII');
insert into models values(157,'Mercury','Mystique');
insert into models values(158,'Mercury','Cougar');
insert into models values(159,'Buick','Park Avenue');
insert into models values(160,'Buick','Riviera');
insert into models values(161,'Audi','A6');
insert into models values(162,'Mazda','B-Series Plus');
insert into models values(163,'Mazda','Miata MX-5');
insert into models values(164,'Mitsubishi','Pajero');
insert into models values(165,'Mitsubishi','Expo LRV');
insert into models values(166,'Suzuki','Swift');
insert into models values(167,'Chevrolet','2500');
insert into models values(168,'Chevrolet','Lumina');
insert into models values(169,'Land Rover','Discovery');
insert into models values(170,'Nissan','Maxima');
insert into models values(171,'Lexus','LX');
insert into models values(172,'Lotus','Esprit');
insert into models values(173,'Eagle','Summit');
insert into models values(174,'Eagle','Talon');
insert into models values(175,'GMC','Rally Wagon G3500');
insert into models values(176,'Oldsmobile','Aurora');
insert into models values(177,'Toyota','Celica');
insert into models values(178,'Isuzu','Space');
insert into models values(179,'Isuzu','Stylus');
insert into models values(180,'Plymouth','Colt Vista');
insert into models values(181,'Volkswagen','Golf III');
insert into models values(182,'Dodge','Ram Van B250');
insert into models values(183,'Dodge','Ram Wagon B150');
insert into models values(184,'Dodge','Shadow');
insert into models values(185,'Chevrolet','G-Series G20');
insert into models values(186,'Subaru','Loyale');
insert into models values(187,'Lotus','Elan');
insert into models values(188,'Acura','Vigor');
insert into models values(189,'Lincoln','Navigator');
insert into models values(190,'Honda','CR-V');
insert into models values(191,'Cadillac','Catera');
insert into models values(192,'Chrysler','Fifth Ave');
insert into models values(193,'Ford','Festiva');
insert into models values(194,'Mercedes-Benz','300SL');
insert into models values(195,'Dodge','D150');
insert into models values(196,'Chevrolet','APV');
insert into models values(197,'Saturn','Ion');
insert into models values(198,'Volvo','XC70');
insert into models values(199,'Pontiac','Daewoo Kalos');
insert into models values(200,'Pontiac','Montana SV6');
insert into models values(201,'Ford','Escape');
insert into models values(202,'Ford','Focus');
insert into models values(203,'Ford','Explorer Sport Trac');
insert into models values(204,'Buick','Terraza');
insert into models values(205,'Buick','Rainier');
insert into models values(206,'Suzuki','Verona');
insert into models values(207,'BMW','525');
insert into models values(208,'Mitsubishi','Endeavor');
insert into models values(209,'Cadillac','STS');
insert into models values(210,'Toyota','Matrix');
insert into models values(211,'Lotus','Exige');
insert into models values(212,'Kia','Amanti');
insert into models values(213,'Mercury','Monterey');
insert into models values(214,'Chevrolet','Silverado');
insert into models values(215,'Chevrolet','Silverado 1500');
insert into models values(216,'MINI','MINI');
insert into models values(217,'Daewoo','Leganza');
insert into models values(218,'Volkswagen','R32');
insert into models values(219,'Chevrolet','Aveo');
insert into models values(220,'Chevrolet','SSR');
insert into models values(221,'Lamborghini','Murci?lago');
insert into models values(222,'GMC','Envoy XUV');
insert into models values(223,'Oldsmobile','Intrigue');
insert into models values(224,'Subaru','Outback Sport');
insert into models values(225,'Dodge','Charger');
insert into models values(226,'Toyota','Supra');
insert into models values(227,'Dodge','Caravan');
insert into models values(228,'Dodge','Ram 3500 Club');
insert into models values(229,'Ford','Ranger');
insert into models values(230,'Ford','Probe');
insert into models values(231,'Ford','Econoline E150');
insert into models values(232,'Ford','F250');
insert into models values(233,'Mercedes-Benz','S-Class');
insert into models values(234,'Mercedes-Benz','E-Class');
insert into models values(235,'Buick','LeSabre');
insert into models values(236,'Mazda','MX-6');
insert into models values(237,'Mazda','Protege');
insert into models values(238,'Volkswagen','Passat');
insert into models values(239,'Volkswagen','GTI');
insert into models values(240,'Volkswagen','rio');
insert into models values(241,'Mitsubishi','Chariot');
insert into models values(242,'Saab','9000');
insert into models values(243,'Holden','VS Commodore');
insert into models values(244,'Plymouth','Grand Voyager');
insert into models values(245,'Chevrolet','Blazer');
insert into models values(246,'Chevrolet','Corsica');
insert into models values(247,'Chevrolet','Sportvan G30');
insert into models values(248,'Nissan','Pathfinder');
insert into models values(249,'Chrysler','New Yorker');
insert into models values(250,'BMW','8 Series');
insert into models values(251,'GMC','2500');
insert into models values(252,'GMC','1500 Club Coupe');
insert into models values(253,'GMC','Sonoma Club Coupe');
insert into models values(254,'GMC','Yukon');
insert into models values(255,'Isuzu','Oasis');
insert into models values(256,'Toyota','4Runner');
insert into models values(257,'Toyota','Avalon');
insert into models values(258,'Toyota','RAV4');
insert into models values(259,'Chevrolet','Sportvan G20');
insert into models values(260,'GMC','Vandura 3500');
insert into models values(261,'Hyundai','Excel');
insert into models values(262,'Oldsmobile','Cutlass Cruiser');
insert into models values(263,'Buick','Coachbuilder');
insert into models values(264,'Mitsubishi','Mighty Max Macro');
insert into models values(265,'Volkswagen','Corrado');
insert into models values(266,'Mazda','323');
insert into models values(267,'Chevrolet','K5 Blazer');
insert into models values(268,'GMC','Rally Wagon G2500');
insert into models values(269,'Mitsubishi','Challenger');
insert into models values(270,'Ford','Expedition');
insert into models values(271,'Plymouth','Prowler');
insert into models values(272,'Acura','CL');
insert into models values(273,'Jeep','Comanche');
insert into models values(274,'Volvo','740');
insert into models values(275,'Mercedes-Benz','300D');
insert into models values(276,'Dodge','D250');
insert into models values(277,'Dodge','Ram 50');
insert into models values(278,'Volkswagen','riolet');
insert into models values(279,'BMW','M5');
insert into models values(280,'Chevrolet','Lumina APV');
insert into models values(281,'Volvo','S40');
insert into models values(282,'Volvo','XC90');
insert into models values(283,'Acura','RSX');
insert into models values(284,'Pontiac','Aztek');
insert into models values(285,'Pontiac','Vibe');
insert into models values(286,'Ford','E350');
insert into models values(287,'Suzuki','Daewoo Magnus');
insert into models values(288,'Suzuki','Reno');
insert into models values(289,'Mercedes-Benz','M-Class');
insert into models values(290,'Honda','Element');
insert into models values(291,'Audi','Allroad');
insert into models values(292,'Cadillac','Escalade');
insert into models values(293,'Toyota','Solara');
insert into models values(294,'Holden','Monaro');
insert into models values(295,'Nissan','Xterra');
insert into models values(296,'Chrysler','300M');
insert into models values(297,'Chrysler','PT Cruiser');
insert into models values(298,'Infiniti','FX');
insert into models values(299,'Corbin','Sparrow');
insert into models values(300,'GMC','Canyon');
insert into models values(301,'HUMMER','H2');
insert into models values(302,'Pontiac','Firebird Formula');
insert into models values(303,'Ford','Escort ZX2');
insert into models values(304,'Audi','RS6');
insert into models values(305,'Toyota','Corolla');
insert into models values(306,'Toyota','Land Cruiser');
insert into models values(307,'Dodge','Dakota');
insert into models values(308,'Dodge','Grand Caravan');
insert into models values(309,'Dodge','Neon');
insert into models values(310,'Dodge','Ram 1500 Club');
insert into models values(311,'Dodge','Ram 1500');
insert into models values(312,'Dodge','Ram 2500 Club');
insert into models values(313,'Dodge','Ram Van 1500');
insert into models values(314,'Ford','Mustang');
insert into models values(315,'Mercury','Sable');
insert into models values(316,'Mercury','Villager');
insert into models values(317,'Buick','Roadmaster');
insert into models values(318,'Audi','riolet');
insert into models values(319,'Mazda','MX-3');
insert into models values(320,'Mazda','MPV');
insert into models values(321,'Mitsubishi','Diamante');
insert into models values(322,'Mitsubishi','3000GT');
insert into models values(323,'Pontiac','Firebird');
insert into models values(324,'Plymouth','Neon');
insert into models values(325,'Chevrolet','G-Series 1500');
insert into models values(326,'Nissan','240SX');
insert into models values(327,'Nissan','Altima');
insert into models values(328,'Nissan','Quest');
insert into models values(329,'Honda','del Sol');
insert into models values(330,'Chrysler','Sebring');
insert into models values(331,'Acura','Integra');
insert into models values(332,'Eagle','Vision');
insert into models values(333,'GMC','3500');
insert into models values(334,'GMC','3500 Club Coupe');
insert into models values(335,'Hyundai','Elantra');
insert into models values(336,'Hyundai','Sonata');
insert into models values(337,'Oldsmobile','98');
insert into models values(338,'Saturn','S-Series');
insert into models values(339,'Toyota','Camry');
insert into models values(340,'GMC','Vandura 1500');
insert into models values(341,'Mercury','Topaz');
insert into models values(342,'Mitsubishi','Precis');
insert into models values(343,'Volkswagen','Jetta III');
insert into models values(344,'Dodge','Viper RT/10');
insert into models values(345,'Chevrolet','G-Series G10');
insert into models values(346,'Chevrolet','S10 Blazer');
insert into models values(347,'Audi','S4');
insert into models values(348,'Audi','Quattro');
insert into models values(349,'Mazda','929');
insert into models values(350,'Mazda','Navajo');
insert into models values(351,'Suzuki','SJ');
insert into models values(352,'Suzuki','Samurai');
insert into models values(353,'Porsche','928');
insert into models values(354,'Chevrolet','G-Series 3500');
insert into models values(355,'Chrysler','Imperial');
insert into models values(356,'Mercedes-Benz','W201');
insert into models values(357,'Mercedes-Benz','600SEC');
insert into models values(358,'Dodge','D350');
insert into models values(359,'Volvo','V40');
insert into models values(360,'Ford','GT');
insert into models values(361,'BMW','6 Series');
insert into models values(362,'BMW','530');
insert into models values(363,'BMW','760');
insert into models values(364,'Honda','Civic Si');
insert into models values(365,'Maserati','Gran Sport');
insert into models values(366,'Lotus','Elise');
insert into models values(367,'Lexus','IS');
insert into models values(368,'Kia','Optima');
insert into models values(369,'Kia','Spectra');
insert into models values(370,'Suzuki','Vitara');
insert into models values(371,'Subaru','Baja');
insert into models values(372,'Subaru','Outback');
insert into models values(373,'GMC','Sierra 3500');
insert into models values(374,'GMC','Yukon XL 1500');
insert into models values(375,'Chevrolet','Trailblazer');
insert into models values(376,'Nissan','Frontier');
insert into models values(377,'Dodge','Durango');
insert into models values(378,'Jaguar','X-Type');
insert into models values(379,'Chevrolet','Classic');
insert into models values(380,'Nissan','350Z');
insert into models values(381,'GMC','EV1');
insert into models values(382,'Chrysler','300');
insert into models values(383,'Isuzu','VehiCROSS');
insert into models values(384,'Chrysler','Grand Voyager');
insert into models values(385,'Mazda','B2500');
insert into models values(386,'Honda','Civic GX');
insert into models values(387,'Audi','RS 6');
insert into models values(388,'Toyota','Tercel');
insert into models values(389,'Volvo','940');
insert into models values(390,'Ford','Contour');
insert into models values(391,'Ford','Explorer');
insert into models values(392,'Ford','F-Series');
insert into models values(393,'Ford','F150');
insert into models values(394,'Mercedes-Benz','C-Class');
insert into models values(395,'Mercury','Grand Marquis');
insert into models values(396,'Volkswagen','Cabriolet');
insert into models values(397,'Volkswagen','Golf');
insert into models values(398,'Mitsubishi','Truck');
insert into models values(399,'Mitsubishi','GTO');
insert into models values(400,'Suzuki','Sidekick');
insert into models values(401,'Plymouth','Voyager');
insert into models values(402,'Plymouth','Breeze');
insert into models values(403,'Chevrolet','Cavalier');
insert into models values(404,'Chevrolet','Corvette');
insert into models values(405,'Land Rover','Range Rover');
insert into models values(406,'Nissan','300ZX');
insert into models values(407,'Nissan','200SX');
insert into models values(408,'Kia','Sportage');
insert into models values(409,'Subaru','Alcyone SVX');
insert into models values(410,'Honda','Accord');
insert into models values(411,'BMW','3 Series');
insert into models values(412,'Acura','NSX');
insert into models values(413,'Cadillac','Fleetwood');
insert into models values(414,'GMC','Safari');
insert into models values(415,'GMC','Suburban 1500');
insert into models values(416,'GMC','Suburban 2500');
insert into models values(417,'GMC','Vandura G3500');
insert into models values(418,'HUMMER','H1');
insert into models values(419,'Infiniti','I');
insert into models values(420,'Infiniti','J');
insert into models values(421,'Infiniti','Q');
insert into models values(422,'Isuzu','Trooper');
insert into models values(423,'Oldsmobile','88');
insert into models values(424,'Oldsmobile','Cutlass Supreme');
insert into models values(425,'Kia','Mentor');
insert into models values(426,'Mercury','Mountaineer');
insert into models values(427,'GMC','Rally Wagon 1500');
insert into models values(428,'Plymouth','Laser');
insert into models values(429,'Ford','Lightning');
insert into models values(430,'Mercury','Capri');
insert into models values(431,'Dodge','Colt');
insert into models values(432,'Dodge','Ram Wagon B250');
insert into models values(433,'Land Rover','Defender 90');
insert into models values(434,'Pontiac','Firefly');
insert into models values(435,'Audi','S6');
insert into models values(436,'Infiniti','QX');
insert into models values(437,'Isuzu','Hombre Space');
insert into models values(438,'Mercedes-Benz','190E');
insert into models values(439,'Mercedes-Benz','300SD');
insert into models values(440,'Mercedes-Benz','400E');
insert into models values(441,'Mercedes-Benz','500E');
insert into models values(442,'Mercedes-Benz','500SEL');
insert into models values(443,'Dodge','D250 Club');
insert into models values(444,'Land Rover','Defender 110');
insert into models values(445,'Pontiac','G6');
insert into models values(446,'Pontiac','Monterey');
insert into models values(447,'Ford','Freestyle');
insert into models values(448,'Ford','E150');
insert into models values(449,'Buick','LaCrosse');
insert into models values(450,'Porsche','Cayenne');
insert into models values(451,'Suzuki','Grand Vitara');
insert into models values(452,'Suzuki','XL-7');
insert into models values(453,'Honda','Insight');
insert into models values(454,'Mazda','Mazda3');
insert into models values(455,'Cadillac','SRX');
insert into models values(456,'Cadillac','CTS');
insert into models values(457,'Cadillac','Escalade EXT');
insert into models values(458,'Maserati','Quattroporte');
insert into models values(459,'Toyota','Echo');
insert into models values(460,'Toyota','Highlander');
insert into models values(461,'Lexus','RX');
insert into models values(462,'Spyker','C8 Spyder Wide Body');
insert into models values(463,'Audi','S8');
insert into models values(464,'BMW','M');
insert into models values(465,'GMC','Sierra 1500');
insert into models values(466,'GMC','Sierra 2500');
insert into models values(467,'Daewoo','Nubira');
insert into models values(468,'Lamborghini','Gallardo');
insert into models values(469,'Volvo','S70');
insert into models values(470,'Ford','TH!NK');
insert into models values(471,'Toyota','MR2');
insert into models values(472,'Dodge','Avenger');
insert into models values(473,'Dodge','Ram 2500');
insert into models values(474,'Dodge','Ram 3500');
insert into models values(475,'Mazda','MX-5');
insert into models values(476,'Mazda','B-Series');
insert into models values(477,'Mazda','Millenia');
insert into models values(478,'Pontiac','Grand Am');
insert into models values(479,'Pontiac','Bonneville');
insert into models values(480,'Chevrolet','1500');
insert into models values(481,'Chevrolet','Astro');
insert into models values(482,'Chevrolet','Impala');
insert into models values(483,'Chevrolet','Caprice');
insert into models values(484,'Chevrolet','Express 1500');
insert into models values(485,'Chrysler','Town  Country');
insert into models values(486,'Chrysler','Concorde');
insert into models values(487,'Acura','TL');
insert into models values(488,'Geo','Prizm');
insert into models values(489,'GMC','2500 Club Coupe');
insert into models values(490,'GMC','Sonoma');
insert into models values(491,'Hyundai','Accent');
insert into models values(492,'Oldsmobile','Achieva');
insert into models values(493,'GMC','Vandura 2500');
insert into models values(494,'Isuzu','Amigo');
insert into models values(495,'Plymouth','Acclaim');
insert into models values(496,'Ford','Tempo');
insert into models values(497,'Dodge','Ram');
insert into models values(498,'Dodge','Spirit');
insert into models values(499,'Audi','90');
insert into models values(500,'Audi','V8');
insert into models values(501,'Acura','Legend');
insert into models values(502,'Chrysler','LeBaron');
insert into models values(503,'Mitsubishi','Montero Sport');
insert into models values(504,'Mercedes-Benz','SLK-Class');
insert into models values(505,'Chevrolet','Malibu');
insert into models values(506,'Oldsmobile','Cutlass');
insert into models values(507,'Volvo','V90');
insert into models values(508,'Daihatsu','Rocky');
insert into models values(509,'Isuzu','Impulse');
insert into models values(510,'Pontiac','LeMans');
insert into models values(511,'Ford','LTD Crown Victoria');
insert into models values(512,'Mercedes-Benz','300SE');
insert into models values(513,'Mercedes-Benz','400SEL');
insert into models values(514,'Mercedes-Benz','500SEC');
insert into models values(515,'Mercedes-Benz','500SL');
insert into models values(516,'Dodge','Daytona');
insert into models values(517,'Volkswagen','Fox');
insert into models values(518,'Land Rover','Range Rover Classic');
insert into models values(519,'Nissan','NX');
insert into models values(520,'Oldsmobile','Alero');
insert into models values(521,'Saturn','L-Series');
insert into models values(522,'Volvo','S60');
insert into models values(523,'Volvo','V70');
insert into models values(524,'Volkswagen','Phaeton');
insert into models values(525,'Acura','MDX');
insert into models values(526,'Pontiac','GTO');
insert into models values(527,'Suzuki','Aerio');
insert into models values(528,'Mercedes-Benz','CLK-Class');
insert into models values(529,'Mercedes-Benz','CL-Class');
insert into models values(530,'Mercedes-Benz','G-Class');
insert into models values(531,'BMW','325');
insert into models values(532,'BMW','330');
insert into models values(533,'BMW','545');
insert into models values(534,'BMW','Z4');
insert into models values(535,'Honda','Pilot');
insert into models values(536,'Toyota','Sienna');
insert into models values(537,'Kia','Sorento');
insert into models values(538,'Kia','Sedona');
insert into models values(539,'MINI','Cooper');
insert into models values(540,'Saab','9-3');
insert into models values(541,'BMW','Z8');
insert into models values(542,'Lincoln','Blackwood');
insert into models values(543,'GMC','Envoy');
insert into models values(544,'Chrysler','Voyager');
insert into models values(545,'Land Rover','Freelander');
insert into models values(546,'Nissan','Pathfinder Armada');
insert into models values(547,'Ford','Explorer Sport');
insert into models values(548,'Toyota','Ipsum');
insert into models values(549,'GMC','Yukon Denali');
insert into models values(550,'Toyota','Previa');
insert into models values(551,'Toyota','Tacoma');
insert into models values(552,'Toyota','Tacoma Xtra');
insert into models values(553,'Dodge','Ram Van 2500');
insert into models values(554,'Ford','Econoline E250');
insert into models values(555,'Mercury','Tracer');
insert into models values(556,'Audi','A4');
insert into models values(557,'Mazda','626');
insert into models values(558,'Mitsubishi','Mirage');
insert into models values(559,'Mitsubishi','Eclipse');
insert into models values(560,'Mitsubishi','Montero');
insert into models values(561,'Chevrolet','Camaro');
insert into models values(562,'Chevrolet','Caprice Classic');
insert into models values(563,'Chevrolet','Monte Carlo');
insert into models values(564,'Chevrolet','Suburban 1500');
insert into models values(565,'Subaru','Legacy');
insert into models values(566,'Subaru','SVX');
insert into models values(567,'Honda','Passport');
insert into models values(568,'Honda','Odyssey');
insert into models values(569,'Honda','Prelude');
insert into models values(570,'BMW','M3');
insert into models values(571,'Acura','RL');
insert into models values(572,'Cadillac','DeVille');
insert into models values(573,'Cadillac','Eldorado');
insert into models values(574,'Cadillac','Seville');
insert into models values(575,'Geo','Metro');
insert into models values(576,'Geo','Tracker');
insert into models values(577,'GMC','Savana 1500');
insert into models values(578,'GMC','Savana 2500');
insert into models values(579,'GMC','Savana 3500');
insert into models values(580,'Jaguar','XJ Series');
insert into models values(581,'Oldsmobile','Bravada');
insert into models values(582,'Geo','Storm');
insert into models values(583,'GMC','Rally Wagon 3500');
insert into models values(584,'Hyundai','Scoupe');
insert into models values(585,'Plymouth','Colt');
insert into models values(586,'Mitsubishi','RVR');
insert into models values(587,'Volkswagen','Eurovan');
insert into models values(588,'Dodge','Ram Wagon B350');
insert into models values(589,'Mazda','RX-7');
insert into models values(590,'Land Rover','Defender');
insert into models values(591,'Pontiac','Sunbird');
insert into models values(592,'Volvo','S90');
insert into models values(593,'Chevrolet','Prizm');
insert into models values(594,'Daihatsu','Charade');
insert into models values(595,'Oldsmobile','Custom Cruiser');
insert into models values(596,'Oldsmobile','Toronado');
insert into models values(597,'Mercedes-Benz','300CE');
insert into models values(598,'Mercedes-Benz','300E');
insert into models values(599,'Mercedes-Benz','600SL');
insert into models values(600,'Dodge','D150 Club');
insert into models values(601,'Dodge','D350 Club');
insert into models values(602,'Dodge','Dynasty');
insert into models values(603,'Cadillac','Allante');
insert into models values(604,'Cadillac','Sixty Special');
insert into models values(605,'Scion','tC');
insert into models values(606,'Pontiac','Montana');
insert into models values(607,'Buick','Rendezvous');
insert into models values(608,'Suzuki','Forenza');
insert into models values(609,'Mercedes-Benz','SLR McLaren');
insert into models values(610,'Mitsubishi','Lancer Evolution');
insert into models values(611,'Honda','S2000');
insert into models values(612,'Mazda','Mazda6');
insert into models values(613,'Mazda','Tribute');
insert into models values(614,'Mazda','RX-8');
insert into models values(615,'Toyota','Tundra');
insert into models values(616,'Kia','Rio');
insert into models values(617,'Spyker','C8 Laviolette');
insert into models values(618,'Saab','9-5');
insert into models values(619,'GMC','Envoy XL');
insert into models values(620,'GMC','Yukon XL 2500');
insert into models values(621,'Chevrolet','Avalanche');
insert into models values(622,'Chevrolet','Avalanche 2500');
insert into models values(623,'Chevrolet','Silverado 2500');
insert into models values(624,'Chevrolet','Silverado 3500');
insert into models values(625,'Chrysler','Prowler');
insert into models values(626,'Daewoo','Lanos');
insert into models values(627,'Hyundai','Santa Fe');
insert into models values(628,'Lincoln','Aviator');
insert into models values(629,'Chevrolet','TrailBlazer');
insert into models values(630,'Maybach','57');
insert into models values(631,'Isuzu','Ascender');

/
COMMIT /

create materialized view manufacturers  /* REFRESH FAST FOR UPDATE */
as select distinct make from models;